from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional, Sequence
import time

from instancespace import InstanceSpace
from instancespace.data import metadata as isa_metadata
from instancespace.data.options import InstanceSpaceOptions, from_json_file, PerformanceOptions

from common.file_utils import BASE_RESULTS_PATH, ensure_dir

ISA_RESULTS_DIR = BASE_RESULTS_PATH / "isa"
DEFAULT_DATASET_PATH = ISA_RESULTS_DIR / "instancespace_dataset.csv"
DEFAULT_OUTPUT_DIR = ISA_RESULTS_DIR / f"analysis_{str(time.time_ns())}"


class InstanceSpaceAnalysisError(RuntimeError):
    """Raised when the ISA pipeline cannot be executed."""


def _load_options(options_path: Optional[Path]) -> InstanceSpaceOptions:
    if options_path is None:
        perf = PerformanceOptions.default(
            max_perf=True,
            abs_perf=False,
            epsilon = 0.02,
            beta_threshold = 0.55,
        )
        return InstanceSpaceOptions.default(
            parallel=None,
            perf=perf,
            auto=None,
            bound=None,
            norm=None,
            selvars=None,
            sifted=None,
            pilot=None,
            cloister=None,
            pythia=None,
            trace=None,
            outputs=None,
        )

    options = from_json_file(options_path)
    if options is None:
        raise InstanceSpaceAnalysisError(f"Failed to read Instance Space options from '{options_path}'.")
    return options


def _load_metadata(dataset_path: Path):
    metadata = isa_metadata.from_csv_file(dataset_path)
    if metadata is None:
        raise InstanceSpaceAnalysisError(f"Could not parse dataset '{dataset_path}'.")
    if not metadata.feature_names:
        raise InstanceSpaceAnalysisError("The dataset does not contain any 'feature_' columns.")
    if not metadata.algorithm_names:
        raise InstanceSpaceAnalysisError("The dataset does not contain any 'algo_' columns.")
    return metadata


def run_instance_space_analysis(
    dataset_path: Path,
    output_dir: Path,
    options_path: Optional[Path] = None,
) -> None:
    dataset_path = dataset_path.expanduser()
    if not dataset_path.is_file():
        raise InstanceSpaceAnalysisError(f"Dataset not found: '{dataset_path}'.")

    metadata = _load_metadata(dataset_path)
    options = _load_options(options_path)

    print(
        "[isa] Running Instance Space Analysis on "
        f"{len(metadata.instance_labels)} instances, "
        f"{len(metadata.feature_names)} features, "
        f"{len(metadata.algorithm_names)} algorithms."
    )

    instance_space = InstanceSpace(metadata, options)
    print(f"[isa] Instance created. Building...")
    model = instance_space.build()
    print(f"[isa] Build completed. Saving...")

    output_dir = output_dir.expanduser()
    ensure_dir(output_dir)

    if options.outputs.csv:
        model.save_to_csv(output_dir)
    if options.outputs.web:
        model.save_for_web(output_dir)
    if options.outputs.png:
        model.save_graphs(output_dir)

    print(f"[isa] Analysis stored under '{output_dir}'.")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run Instance Space Analysis using the precomputed ISA dataset."
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Path to the CSV file generated by build_isa_dataset.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where ISA outputs (CSVs, PNGs, etc.) will be stored.",
    )
    parser.add_argument(
        "--options",
        type=Path,
        default=None,
        help="Optional JSON file overriding Instance Space options.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> None:
    args = parse_args(argv)
    try:
        run_instance_space_analysis(args.dataset, args.output, args.options)
    except InstanceSpaceAnalysisError as err:
        print(f"[isa] {err}")
        raise SystemExit(1) from err


if __name__ == "__main__":
    main()
