a2c:
  conservative:
    learning_rate: 0.000208
    n_steps: 6
    gamma: 0.9198
    gae_lambda: 0.88
    ent_coef: 0.004
  balanced:
    learning_rate: 0.000505
    n_steps: 11
    gamma: 0.9495
    gae_lambda: 0.925
    ent_coef: 0.01
  aggressive:
    learning_rate: 0.000802
    n_steps: 16
    gamma: 0.9792
    gae_lambda: 0.97
    ent_coef: 0.016

ppo:
  conservative:
    learning_rate: 0.000208
    n_steps: 1229
    gamma: 0.9198
    gae_lambda: 0.88
    ent_coef: 0.004
    clip_range: 0.14
    batch_size: 128
    n_epochs: 4
  balanced:
    learning_rate: 0.000505
    n_steps: 2304
    gamma: 0.9495
    gae_lambda: 0.925
    ent_coef: 0.01
    clip_range: 0.2
    batch_size: 272
    n_epochs: 7
  aggressive:
    learning_rate: 0.000802
    n_steps: 3379
    gamma: 0.9792
    gae_lambda: 0.97
    ent_coef: 0.016
    clip_range: 0.26
    batch_size: 416
    n_epochs: 9

dqn:
  conservative:
    learning_rate: 0.000208
    n_steps: 2
    gamma: 0.9198
    batch_size: 77
    buffer_size: 240000
    learning_starts: 180
    train_freq: 2
    gradient_steps: 2
    target_update_interval: 2800
    exploration_fraction: 0.12
    exploration_final_eps: 0.028
  balanced:
    learning_rate: 0.000505
    n_steps: 3
    gamma: 0.9495
    batch_size: 144
    buffer_size: 525000
    learning_starts: 300
    train_freq: 5
    gradient_steps: 5
    target_update_interval: 5500
    exploration_fraction: 0.15
    exploration_final_eps: 0.055
  aggressive:
    learning_rate: 0.000802
    n_steps: 4
    gamma: 0.9792
    batch_size: 211
    buffer_size: 810000
    learning_starts: 420
    train_freq: 7
    gradient_steps: 7
    target_update_interval: 8200
    exploration_fraction: 0.18
    exploration_final_eps: 0.082
